services:
  - type: web
    name: oceantrace-api
    runtime: python
    plan: free
    branch: production
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CORS_ORIGINS
        value: "*"
